import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { PROJECTS } from './projects';

interface ManifestEntry {
  url: string;
  bytes: number;
  group: string;
}

/**
 * `public/assets/manifest.json` is generated by `npm run assets:optimize` but committed, so it can
 * drift from the models on disk and from the grouping rule in projects.ts. This pins both.
 */
describe('assets manifest', () => {
  const manifest = JSON.parse(readFileSync('public/assets/manifest.json', 'utf8')) as {
    assets: ManifestEntry[];
  };
  const byUrl = new Map(manifest.assets.map((entry) => [entry.url, entry]));

  it('lists every optimised model on disk', () => {
    for (const file of readdirSync('public/assets/models').filter((f) => f.endsWith('.glb'))) {
      expect(byUrl.has(`assets/models/${file}`), file).toBe(true);
    }
  });

  it('only lists files that exist', () => {
    for (const entry of manifest.assets) {
      expect(existsSync(`public/${entry.url}`), entry.url).toBe(true);
    }
  });

  it('groups a model under the project that names it, everything else under core', () => {
    const owners = new Map(
      PROJECTS.filter((p) => p.landmark.model).map((p) => [p.landmark.model, p.slug]),
    );
    for (const entry of manifest.assets.filter((e) => e.url.endsWith('.glb'))) {
      expect(entry.group, entry.url).toBe(owners.get(entry.url) ?? 'core');
    }
  });

  it('groups every screenshot under its project', () => {
    for (const project of PROJECTS) {
      if (project.demo.kind === 'iframe') {
        expect(byUrl.get(project.demo.screenshot)?.group).toBe(project.slug);
      }
    }
  });
});
